apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modresorts
  name: modresorts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modresorts
  template:
    metadata:
      labels:
        app: modresorts
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/modresorts/modresorts:latest
          imagePullPolicy: Always
          name: modresorts
          ports:
            - containerPort: 9080
              protocol: TCP
