# Generated by IBM TransformationAdvisor
# Wed May 05 19:05:52 UTC 2021
# Modified by Tyler Stanczak and Santosh Gurijala

# May need to modify the builder (maven) image tag to match the needed JDK version
# See https://hub.docker.com/_/maven for available image tags
FROM maven:3.3-jdk-8 as builder
WORKDIR /git
COPY . /git
RUN mvn clean install

FROM ibmcom/websphere-traditional:8.5.5.17-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --from=builder --chown=was:root /git/data/examples/*.war /work/config/
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
